// Default mock data used by the API route handler. Individual scenes can
// override any of these by exporting `fixtures` from the scene file.
//
// Keep entries synthetic — no real subjects/addresses lifted from anyone's
// inbox. The point of the data is to exercise UI branches (every bucket,
// every triage path, every pipeline stage), not to look realistic.

export const me = { email: "demo@example.com", user_id: 1 };

const minutesAgo = (m) => new Date(Date.now() - m * 60_000).toISOString();

const base = {
  slug: "",
  keywords: [],
  summary: "",
  labels_applied: [],
  reasoning: "",
  human_feedback: "",
  feedback_dirty: false,
};

export const emails = [
  {
    ...base,
    id: "s1",
    from_address: "security@acme-demo.test",
    subject: "Verification code: 123456",
    bypassed_inbox: false,
    notification_sent: true,
    processed_at: minutesAgo(5),
    created_at: minutesAgo(5),
    bucket: "security",
    pipeline_stage: "processed",
    triage_via: "ai",
  },
  {
    ...base,
    id: "n1",
    from_address: "alerts@socialnet.test",
    subject: "You have 7 new connection requests",
    bypassed_inbox: true,
    notification_sent: false,
    processed_at: minutesAgo(20),
    created_at: minutesAgo(20),
    bucket: "notification",
    pipeline_stage: "processed",
    triage_via: "consistent_sender",
    severity: "low",
    urgency: "low",
  },
  {
    ...base,
    id: "n2",
    from_address: "noreply@socialnet.test",
    subject: "Weekly activity summary",
    bypassed_inbox: true,
    notification_sent: false,
    processed_at: minutesAgo(45),
    created_at: minutesAgo(45),
    bucket: "notification",
    pipeline_stage: "processed",
    triage_via: "ai",
    severity: "low",
    urgency: "low",
  },
  {
    ...base,
    id: "nl1",
    from_address: "deals@shopdemo.test",
    subject: "Picks we think you'll like",
    bypassed_inbox: true,
    notification_sent: false,
    processed_at: minutesAgo(70),
    created_at: minutesAgo(70),
    bucket: "newsletter",
    pipeline_stage: "processed",
    triage_via: "consistent_sender",
    interesting_score: 3,
    interesting_reasons: [],
  },
  {
    ...base,
    id: "nl2",
    from_address: "weekly@news-demo.test",
    subject: "This week in fictional news",
    bypassed_inbox: true,
    notification_sent: false,
    processed_at: minutesAgo(90),
    created_at: minutesAgo(90),
    bucket: "newsletter",
    pipeline_stage: "processed",
    triage_via: "ai",
    interesting_score: 5,
    interesting_reasons: [],
  },
  {
    ...base,
    id: "nl3",
    from_address: "digest@reading-demo.test",
    subject: "Your reading digest",
    bypassed_inbox: true,
    notification_sent: false,
    processed_at: minutesAgo(120),
    created_at: minutesAgo(120),
    bucket: "newsletter",
    pipeline_stage: "processed",
    triage_via: "consistent_sender",
    interesting_score: 4,
    interesting_reasons: [],
  },
  {
    ...base,
    id: "h1",
    from_address: "sample.person@example.test",
    subject: "Re: thanks for catching up",
    bypassed_inbox: false,
    notification_sent: false,
    processed_at: minutesAgo(150),
    created_at: minutesAgo(150),
    bucket: "human",
    pipeline_stage: "processed",
    triage_via: "thread_reply",
  },
  {
    ...base,
    id: "t1",
    from_address: "receipts@billing-demo.test",
    subject: "Receipt for order #4421",
    bypassed_inbox: true,
    notification_sent: false,
    processed_at: minutesAgo(200),
    created_at: minutesAgo(200),
    bucket: "transactional",
    pipeline_stage: "processed",
    triage_via: "consistent_sender",
  },
  {
    ...base,
    id: "c1",
    from_address: "no-reply@cal-demo.test",
    subject: "Invitation: Demo sync",
    bypassed_inbox: false,
    notification_sent: false,
    processed_at: minutesAgo(260),
    created_at: minutesAgo(260),
    bucket: "calendar",
    pipeline_stage: "bucketed",
    triage_via: "ai",
  },
];
