ALTER TABLE users ADD COLUMN IF NOT EXISTS pushover_user_key TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS pushover_app_token TEXT DEFAULT '';
ALTER TABLE emails ADD COLUMN IF NOT EXISTS notification_sent BOOLEAN NOT NULL DEFAULT FALSE;
