ALTER TABLE users ADD COLUMN IF NOT EXISTS webhook_url TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS webhook_header_key TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS webhook_header_value TEXT DEFAULT '';
